In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv('student_results.xls')
df1

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [ ]:
emt_df = pd.DataFrame()
print(emt_df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
df = pd.read_csv('Fortune_10.csv')
print(df.head())
df1 = pd.read_csv('Fortune_10.csv',usecols=[1,3,5])
print(df1)

   ID             Name            Industry  Inception       Revenue  \
0   1          Lamtone         IT Services       2009  $11,757,018
1   2        Stripfind  Financial Services       2010  $12,329,371
2   3  Canecorporation              Health       2012  $10,597,009
3   4         Mattouch         IT Services       2013  $14,026,934
4   5        Techdrill              Health       2009  $10,573,990

            Expenses    Profit Growth
0  6,482,465 Dollars   5274553    30%
1    916,455 Dollars  11412916    20%
2  7,591,189 Dollars   3005820     7%
3  7,429,377 Dollars   6597557    26%
4  7,435,363 Dollars   3138627     8%
              Name  Inception           Expenses
0          Lamtone       2009  6,482,465 Dollars
1        Stripfind       2010    916,455 Dollars
2  Canecorporation       2012  7,591,189 Dollars
3         Mattouch       2013  7,429,377 Dollars
4        Techdrill       2009  7,435,363 Dollars
5         Techline       2006  5,470,303 Dollars
6          Cityace       2010  6,249,498 Dollars
7   Kayelectronics       2009  3,878,113 Dollars
8          Ganzlax       2011                NaN
9      Trantraxlax       2011  5,635,276 Dollars

In [ ]:
df = pd.read_csv('Fortune_10.csv',skiprows=[1,3,5])
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
2,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
3,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
4,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
5,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
6,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv('Fortune_10.csv',skiprows=[1,3,4])
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
2,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
3,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
4,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
5,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
6,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv('Fortune_10.csv',index_col='Name')
df

,ID,Industry,Inception,Revenue,Expenses,Profit,Growth
Name,,,,,,,
Lamtone,1,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
Stripfind,2,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
Canecorporation,3,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
Mattouch,4,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
Techdrill,5,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
Techline,6,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
Cityace,7,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
Kayelectronics,8,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
Ganzlax,9,IT Services,2011,"$14,001,180",NaN,11901180,18%
Trantraxlax,10,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv('Fortune_10.csv',index_col=3)
df

,ID,Name,Industry,Revenue,Expenses,Profit,Growth
Inception,,,,,,,
2009,1,Lamtone,IT Services,"$11,757,018","6,482,465 Dollars",5274553,30%
2010,2,Stripfind,Financial Services,"$12,329,371","916,455 Dollars",11412916,20%
2012,3,Canecorporation,Health,"$10,597,009","7,591,189 Dollars",3005820,7%
2013,4,Mattouch,IT Services,"$14,026,934","7,429,377 Dollars",6597557,26%
2009,5,Techdrill,Health,"$10,573,990","7,435,363 Dollars",3138627,8%
2006,6,Techline,Health,"$13,898,119","5,470,303 Dollars",8427816,23%
2010,7,Cityace,Health,"$9,254,614","6,249,498 Dollars",3005116,6%
2009,8,Kayelectronics,Health,"$9,451,943","3,878,113 Dollars",5573830,4%
2011,9,Ganzlax,IT Services,"$14,001,180",NaN,11901180,18%
2011,10,Trantraxlax,Government Services,"$11,088,336","5,635,276 Dollars",5453060,7%

**Headers**

In [ ]:
df = pd.read_csv('Fortune_10.csv',header= None)
df

,0,1,2,3,4,5,6,7
0,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
1,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv('Fortune_10.csv',names =['A','B','C'])
df

,,,,,A,B,C
ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv('Fortune_10.csv',dtype={'ID':'float64','profit':'float64'})
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4.0,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5.0,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6.0,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7.0,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8.0,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10.0,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df = pd.read_csv('Fortune_10.csv',dtype={'ID':'float64','Inception':'float64'})
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6.0,Techline,Health,2006.0,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7.0,Cityace,Health,2010.0,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8.0,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9.0,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180,18%
9,10.0,Trantraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060,7%

**Nan Values**

In [ ]:
df2 = pd.read_csv('Fortune_10 - Copy.csv')
df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df2 = pd.read_csv('Fortune_10 - Copy.csv',na_values='not available')
df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,NaN
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df2 = pd.read_csv('Fortune_10 - Copy.csv',na_values={'Revenue':'not available'})
df2

FileNotFoundError: [Errno 2] No such file or directory: 'Fortune_10 - Copy.csv'

In [ ]:
df2 = pd.read_csv('Fortune_10 - Copy.csv',keep_default_na=False)
df2

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,no value,"5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,not available
7,8,Kayelectronics,Health,2009,na,"3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [ ]:
df. isnull()

      ID   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  False  False     False      False    False     False   False   False
1  False  False     False      False    False     False   False   False
2  False  False     False      False    False     False   False   False
3  False  False     False      False    False     False   False   False
4  False  False     False      False    False     False   False   False
5  False  False     False      False    False     False   False   False
6  False  False     False      False    False     False   False   False
7  False  False     False      False    False     False   False   False
8  False  False     False      False    False      True   False   False
9  False  False     False      False    False     False   False   False

In [ ]:
df.notnull()

     ID  Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  True  True      True       True     True      True    True    True
1  True  True      True       True     True      True    True    True
2  True  True      True       True     True      True    True    True
3  True  True      True       True     True      True    True    True
4  True  True      True       True     True      True    True    True
5  True  True      True       True     True      True    True    True
6  True  True      True       True     True      True    True    True
7  True  True      True       True     True      True    True    True
8  True  True      True       True     True     False    True    True
9  True  True      True       True     True      True    True    True

In [ ]:
df.dropna(axis=1,how = 'any')

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [ ]:
ser.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [ ]:
df= pd.read_csv('/content/Fortune_5 nan values.csv')
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009",NaN,3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
 df.dropna()

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.dropna(axis = 1)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.dropna(axis=1)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.dropna(how = 'any')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.dropna(axis=1,how = 'any')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.dropna(how = 'all')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.dropna(axis=1,how = 'all')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.dropna(thresh = 1)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.dropna(subset = ['Profit'])

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.fillna({'Expenses':'none','Profit':55})

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.fillna(method = 'ffill')

/tmp/ipykernel_1926/1145651979.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%

In [ ]:
df.fillna(method = 'bfill')

/tmp/ipykernel_1926/3673297803.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1.0,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2.0,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3.0,Canecorporation,Health,2012.0,"$10,597,009","7,429,377 Dollars",3005820.0,7%
3,4.0,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5.0,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",NaN,8%
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**List**

In [ ]:
list = [1,2,3,-3,2.7,'data']
list

[1, 2, 3, -3, 2.7, 'data']

**Series**

In [ ]:
#scalar series

scalar_s= pd.Series(0.5)
scalar_s

0    0.5
dtype: float64

In [ ]:
scalar_s1 = pd.Series(0.5,index=[1,2,3])
scalar_s1

1    0.5
2    0.5
3    0.5
dtype: float64

**Empty Series**

In [ ]:
empty_s = pd.Series([])
type(empty_s)
empty_s

Series([], dtype: object)

**List to Series**